### ISSUE TITLE
"Handler <function mangle_docstrings at 0x7f64b5ba57b8> for event 'autodoc-process-docstring' threw an exception"

### ISSUE THREAD

**Issue by arokem** [numpy/numpydoc#268]
We're starting to see this with the upgrade from 0.9.2 to 1.0

For example: https://github.com/yeatmanlab/pyAFQ/pull/270/checks?check_run_id=800934528#step:6:61

See also: https://github.com/yeatmanlab/pyAFQ/pull/271

Do we need to change something on our end?

**Comment by larsoner** [comment]
Possibly there is some error in your docstrings, but numpydoc should just warn about this (and maybe have an ugly output) rather than kill the build.

Is it easy to reproduce, for example by `git clone`ing that repo and just running `make html` in the `docs` dir? If it takes much more than this (needing datasets, etc.) could you try to boil it down to a smaller example that we can run to test?

**Comment by larsoner** [comment]
> Extension error:
> Could not import extension autoapi.extension (exception: No module named 'autoapi')

So I `pip install autoapi`, same error, change `conf.py` to have `autoapi.sphinx`, then get Sphinx-gallery errors about examples, set `sphinx_gallery_conf['plot_gallery'] = False`, then `make html` works just fine. I would try at your end running with `SPHINXOPTS="-nWT --keep-going -vvv"` or so that you get a lot more output and can debug.

For example, is it possible that the bug is with `autoapi` and not with `numpydoc`? Can't tell from the traceback...

Also the link above appears to no longer contain an error (?), so I'm guessing someone restarted the build. I'll close for now but feel free to reopen if you can get a bit more information with a better traceback and/or way to reproduce locally.

**Comment by arokem** [comment]
With `SPHINXOPTS="-nWT --keep-going -vvv"`, the traceback is: 


```
Traceback (most recent call last):
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/numpydoc/numpydoc.py", line 155, in mangle_docstrings
    'xref_aliases': app.config.numpydoc_xref_aliases_complete,
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/sphinx/config.py", line 250, in __getattr__
    raise AttributeError(__('No such config value: %s') % name)
AttributeError: No such config value: numpydoc_xref_aliases_complete

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/sphinx/application.py", line 277, in __init__
    self._init_builder()
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/sphinx/application.py", line 333, in _init_builder
    self.events.emit('builder-inited')
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/autoapi/extension.py", line 129, in run_autoapi
    sphinx_mapper_obj.map(options=app.config.autoapi_options)
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/autoapi/mappers/python/mapper.py", line 275, in map
    super(PythonSphinxMapper, self).map(options)
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/autoapi/mappers/base.py", line 276, in map
    for obj in self.create_class(data, options=options):
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/autoapi/mappers/python/mapper.py", line 317, in create_class
    lines,
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/sphinx/application.py", line 450, in emit
    return self.events.emit(event, *args, allowed_exceptions=allowed_exceptions)
  File "/Users/arokem/.virtualenvs/afq/lib/python3.7/site-packages/sphinx/events.py", line 118, in emit
    (listener.handler, name)) from exc
sphinx.errors.ExtensionError: Handler <function mangle_docstrings at 0x11246fe18> for event 'autodoc-process-docstring' threw an exception

Extension error:
Handler <function mangle_docstrings at 0x11246fe18> for event 'autodoc-process-docstring' threw an exception
make: *** [html] Error 2
```

Indeed, if I add a call to `update_config(app)` [here](https://github.com/numpy/numpydoc/blob/master/numpydoc/numpydoc.py#L145) this error is not raised.

**Comment by larsoner** [comment]
Hmm, shouldn't be necessary to do that. This suggests that `update_config`, which we connect to the `builder-inited`, is not being called before the `'autodoc-process-docstring'` event is emitted. We can pretty easily add a:
```
if not hasattr(app.config, numpydoc_xref_aliases_complete):
    update_config(app)
```
But this feels like a bit of a hack. It would be better to understand why on your build (but no others that have used `xref` so far, and not for me locally) we have that `builder-inited` is not called before `autodoc-process-docstring`.

**Comment by larsoner** [comment]
I would be willing to investigate, but without some minimal example or reproducing environment I cannot...

**Comment by arokem** [comment]
Would cloning/installing pyAFQ and building the docs there be "minimal" enough? I can try to create a branch without the sphinx gallery examples, to reduce the data download requirements.

**Comment by larsoner** [comment]
> Would cloning/installing pyAFQ and building the docs there be "minimal" enough?

That's exactly what I [describe above](https://github.com/numpy/numpydoc/issues/268#issuecomment-649040096). Can you reproduce locally, or just on CI?

**Comment by arokem** [comment]
Yes - [https://github.com/numpy/numpydoc/issues/268#issuecomment-649193723](this) is what I find locally with the current master branch.

**Comment by arokem** [comment]
FWIW, here's a branch without the sphinx gallery examples: https://github.com/arokem/pyAFQ/tree/no_examples

**Comment by larsoner** [comment]
What version of autoapi are you running? I'll need to install that to roll back my changes to `conf.py` because I had to put it in as `autoapi.sphinx` when I just `pip install autoapi` the latest version (as noted above)...

What's interesting is that this on my system only spits out that it runs `builder-inited`:
```
make clean; make html | grep "emit.*\\(builder-inited\\|autodoc\\)"
```
If I run it on MNE-Python with:
```
make clean; make html_dev-noplot SPHINXOPTS="-nWT --keep-going -vvv" | grep "emit.*\\(builder-inited\\|autodoc-process-docstring\\)"
```
I do see the `builder-inited` well before the `autodoc-process-docstrings` pop up.

I wonder if `autoapi` is somehow the culprit here. A possibility at our end is to do `app.connect('config-inited', update_config)` and change to `def update_config(app, cfg=None)`, but first I want to a) confirm it's an `autoapi` interaction by using whatever version you are using locally, and b) confirm it's *not* fixed at your end just by updating `autoapi` and `conf.py` to have `autoapi.sphinx` instead of `autoapi.extension`.

**Comment by arokem** [comment]
I have `sphinx-autoapi==1.2.1`

**Comment by arokem** [comment]
On my end, upgrading sphinx-autoapi to 1.4.0 does not resolve the error.

**Comment by larsoner** [comment]
Okay it is indeed because `sphinx-autoapi` messes with the event order. This is arguably a bug at their end, but I'll see if we can safely just connect to `config-inited` instead of `build-inited`...

**Comment by larsoner** [comment]
#269
